name: Сборка

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Клонировать репозиторий
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Сгенерировать версию
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Установить зависимости
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev \
            build-essential git python3 \
            wget unzip

      - name: Установить Android NDK
        run: |
          mkdir -p $HOME/ndk
          wget https://dl.google.com/android/repository/android-ndk-r29-linux.zip -O $HOME/ndk/android-ndk-r29-linux.zip
          unzip $HOME/ndk/android-ndk-r29-linux.zip -d $HOME/ndk/
          export ANDROID_NDK=$HOME/ndk/android-ndk-r29
          echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      - name: Сборка kpimg
        run: |
          export ANDROID=1
          cd kernel
          export TARGET_COMPILE=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
          make -j$(nproc)  # Сборка с использованием всех доступных процессоров
          
          # Опционально: перемещаем артефакты в нужное место
          mv kpimg kpimg-android
          mv kpimg.elf kpimg.elf-android
          make clean
          
          # Для Linux версии (если нужно)
          unset ANDROID
          make -j$(nproc)
          mv kpimg kpimg-linux
          mv kpimg.elf kpimg.elf-linux
          make clean

      # Шаг 6: 
      - name: Загрузка артефактов
        uses: actions/upload-artifact@v6
        with:
          name: kpimg-artifacts
          path: |
            kernel/kpimg-linux
            kernel/kpimg-android
            kernel/kpimg.elf-linux
            kernel/kpimg.elf-android

      - name: Релиз
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            kernel/kpimg-linux
            kernel/kpimg-android
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true

  Build-android-kptools:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Сгенерировать версию
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: true

      - name: Build kptools-android
        run: |
          cd tools
          mkdir -p build/android && cd build/android
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_PLATFORM=android-31 \
            -DANDROID_ABI=arm64-v8a ../..
          cmake --build .
          mv kptools kptools-android

      - name: Релиз
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            tools/build/android/kptools-android
          allowUpdates: true
          replacesArtifacts: true

  Build-kptools-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Сгенерировать версию
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Сборкаkptools-linux
        run: |
          export ANDROID=1
          cd tools
          mkdir -p build && cd build
          cmake ..
          make
          mv kptools kptools-linux

      - name: Релиз
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            tools/build/kptools-linux
          allowUpdates: true
          replacesArtifacts: true

  Build-kptools-mac:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Клонирую репозитарий
        uses: actions/checkout@v6

      - name: Сгенерировать версию
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Сборка kptools-mac
        run: |
          export ANDROID=1
          cd tools
          mkdir -p build && cd build
          cmake ..
          make
          mv kptools kptools-mac

      - name: Релиз
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            tools/build/kptools-mac
          allowUpdates: true
          replacesArtifacts: true
 
